import 'package:cloud_firestore/cloud_firestore.dart';

/// A document from the Firestore `payments` collection.
///
/// Created when a student pays for a locker booking through the demo payment
/// gateway. The payment record is the audit trail for every transaction —
/// it links the booking, the student, the locker, the card used (last 4
/// digits only — never the full card number or CVV), and the transaction /
/// receipt identifiers generated by the demo gateway.
///
/// `paidAt` stays as an ISO-8601 string on the Dart side; the Firestore
/// document stores a real [Timestamp], converted both ways here.
class Payment {
  /// Firestore document ID. Empty on an object that has not been written yet.
  final String id;

  /// The `lockerBookings` document this payment belongs to.
  final String bookingId;

  /// Campus-issued Student ID of the payer (e.g. `S001`).
  final String studentId;

  /// The locker this payment is for (e.g. `LK-A01`).
  final String lockerId;

  /// Total amount charged (deposit + total rental cost).
  final double amount;

  /// Refundable deposit portion of [amount].
  final double deposit;

  /// Monthly rent at the time of payment.
  final double monthlyRent;

  /// Rental duration in months.
  final int durationMonths;

  /// Payment method label — always 'Card' for the demo gateway.
  final String paymentMethod;

  /// Last 4 digits of the card used. Never stores the full card number.
  final String cardLast4;

  /// Demo-gateway transaction identifier (e.g. `TXN-…`).
  final String transactionId;

  /// Human-readable receipt number (e.g. `RCP-…`).
  final String receiptNumber;

  /// 'Completed', 'Failed', or 'Refund Pending'.
  final String paymentStatus;

  /// ISO-8601 timestamp of the transaction.
  final String paidAt;

  const Payment({
    required this.id,
    required this.bookingId,
    required this.studentId,
    required this.lockerId,
    required this.amount,
    required this.deposit,
    required this.monthlyRent,
    required this.durationMonths,
    required this.paymentMethod,
    required this.cardLast4,
    required this.transactionId,
    required this.receiptNumber,
    required this.paymentStatus,
    required this.paidAt,
  });

  /// Builds a [Payment] from a Firestore document map.
  ///
  /// [id] is the Firestore document key — pass it explicitly when reading a
  /// snapshot (`Payment.fromMap(doc.id, doc.data())`).
  factory Payment.fromMap(String id, Map<String, dynamic> data) {
    return Payment(
      id: id,
      bookingId: data['bookingId']?.toString() ?? '',
      studentId: data['studentId']?.toString() ?? '',
      lockerId: data['lockerId']?.toString() ?? '',
      amount: (data['amount'] as num?)?.toDouble() ?? 0.0,
      deposit: (data['deposit'] as num?)?.toDouble() ?? 0.0,
      monthlyRent: (data['monthlyRent'] as num?)?.toDouble() ?? 10.0,
      durationMonths: (data['durationMonths'] as num?)?.toInt() ?? 6,
      paymentMethod: data['paymentMethod']?.toString() ?? 'Card',
      cardLast4: data['cardLast4']?.toString() ?? '',
      transactionId: data['transactionId']?.toString() ?? '',
      receiptNumber: data['receiptNumber']?.toString() ?? '',
      paymentStatus: data['paymentStatus']?.toString() ?? 'Completed',
      paidAt: _asIso(data['paidAt']),
    );
  }

  /// The payload written when the document is first created.
  ///
  /// [id] is deliberately absent — the Firestore document key is the identity.
  /// `paidAt` is stored as a [Timestamp] so range queries and ordering work.
  Map<String, dynamic> toMap() {
    return {
      'bookingId': bookingId,
      'studentId': studentId,
      'lockerId': lockerId,
      'amount': amount,
      'deposit': deposit,
      'monthlyRent': monthlyRent,
      'durationMonths': durationMonths,
      'paymentMethod': paymentMethod,
      'cardLast4': cardLast4,
      'transactionId': transactionId,
      'receiptNumber': receiptNumber,
      'paymentStatus': paymentStatus,
      'paidAt': _toTimestamp(paidAt),
    };
  }

  Payment copyWith({
    String? id,
    String? bookingId,
    String? studentId,
    String? lockerId,
    double? amount,
    double? deposit,
    double? monthlyRent,
    int? durationMonths,
    String? paymentMethod,
    String? cardLast4,
    String? transactionId,
    String? receiptNumber,
    String? paymentStatus,
    String? paidAt,
  }) {
    return Payment(
      id: id ?? this.id,
      bookingId: bookingId ?? this.bookingId,
      studentId: studentId ?? this.studentId,
      lockerId: lockerId ?? this.lockerId,
      amount: amount ?? this.amount,
      deposit: deposit ?? this.deposit,
      monthlyRent: monthlyRent ?? this.monthlyRent,
      durationMonths: durationMonths ?? this.durationMonths,
      paymentMethod: paymentMethod ?? this.paymentMethod,
      cardLast4: cardLast4 ?? this.cardLast4,
      transactionId: transactionId ?? this.transactionId,
      receiptNumber: receiptNumber ?? this.receiptNumber,
      paymentStatus: paymentStatus ?? this.paymentStatus,
      paidAt: paidAt ?? this.paidAt,
    );
  }

  static String _asIso(Object? value) {
    if (value is Timestamp) return value.toDate().toIso8601String();
    if (value is DateTime) return value.toIso8601String();
    if (value is String) return value;
    return DateTime.now().toIso8601String();
  }

  static Object _toTimestamp(String value) {
    final parsed = DateTime.tryParse(value);
    return parsed == null
        ? FieldValue.serverTimestamp()
        : Timestamp.fromDate(parsed);
  }
}

/// Outcome of a demo payment gateway attempt. Carries the [Payment] on
/// success, or a user-safe failure message that the caller can show directly
/// (e.g. "Your card was declined.").
class PaymentResult {
  final Payment? payment;
  final String? error;
  const PaymentResult.success(this.payment) : error = null;
  const PaymentResult.failure(this.error) : payment = null;
  bool get isSuccess => payment != null;
}
